services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root_password'
      MYSQL_DATABASE: 'votre_db'
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mysql

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db        
      DB_USER: root
      DB_PASSWORD: root_password
      DB_NAME: votre_db
      PORT: 8080

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80" # L'app sera accessible sur http://localhost:3000
    environment:
      # Injecte l'URL du backend dans l'application React
      # 'backend' est le nom du service Docker
      VITE_API_URL: 'http://backend:8080' 

volumes:
  db-data: